components:
  schemas:
    Application:
      description: Represents an application in the platform
      example:
        currentVersion: 2.0.1
        latestUpstreamVersion: 2.1.0
        name: ArgoCD
      properties:
        currentVersion:
          type: string
        latestUpstreamVersion:
          type: string
        name:
          type: string
      title: Root Type for Application
      type: object
    Applications:
      description: Your guess is as good as mine
      example:
      - currentVersion: 2.0.1
        latestUpstreamVersion: 2.1.0
        name: ArgoCD
      - currentVersion: 1.21.7
        latestUpstreamVersion: 1.22.2
        name: Gitea
      items:
        $ref: '#/components/schemas/Application'
      title: Root Type for Applications
      type: array
info:
  contact: {}
  description: 'An API to get all applications in a platform and it''s version and upstream latest version. '
  license:
    name: MIT License
    url: https://opensource.org/licenses/MIT
  title: PlatformUp2Date
  version: 1.0.0
openapi: 3.0.2
paths:
  /v1/application:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Application'
        "404": {}
      tags:
      - application
    parameters:
    - description: name of the application you want to look at
      in: query
      name: name
      required: true
      schema:
        type: string
  /v1/applications:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Applications'
      tags:
      - application
tags:
- description: ""
  name: application
