apiVersion: tekton.dev/v1 # or tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-test
spec:
  params:
    - name: url
      description: "Repository URL to clone from."
      type: string
    - name: revision
      description: "Revision to checkout. (branch, tag, sha, ref, etc...)"
      type: string
      default: ""
    - name: sha
      description: "sha being worked on"
      type: string
      default: ""
  workspaces:
    - name: source
    - name: ssh-directory
  tasks:
    - name: set-pending-status
      taskRef:
        resolver: cluster
        params:
          - name: name
            value: gitea-set-status
          - name: namespace
            value: tekton-pipelines
      params:
        - name: GITEA_TOKEN_SECRET_NAME
          value: git-ci-status-token
        - name: REPO_FULL_NAME
          value: SREYardship/PlatformUp2Date
        - name: GITEA_HOST_URL
          value: git.sreyardship.com
        - name: SHA
          value: $(params.sha)
        - name: DESCRIPTION
          value: "Build has started"
        - name: STATE
          value: pending
        - name: TARGET_URL
          value: https://dashboard.ci.sreyardship.com/#/namespaces/platformup2date/pipelineruns
    - name: git-clone
      taskRef:
        resolver: cluster
        params:
          - name: name 
            value: git-clone  #expects a Workspace named "source"
          - name: namespace 
            value: tekton-pipelines
            
      params:
        - name: url
          value: "$(params.url)"
        - name: revision
          value: "$(params.revision)"
      workspaces:
        - name: output # <- mapping workspace name
          workspace: source
        - name: ssh-directory
          workspace: ssh-directory
    - name: list-files
      runAfter:
        - git-clone
      taskRef:
        name: list-files
      workspaces:
        - name: source
          workspace: source
  finally:
    - name: pipeline-state
      displayName: "Pipeline Final State"
      taskRef:
        resolver: cluster
        params:
          - name: name
            value: gitea-set-status
          - name: namespace
            value: tekton-pipelines
          - name: pipelineStatus
            value: "$(tasks.status)"
      params:
        - name: GITEA_TOKEN_SECRET_NAME
          value: git-ci-status-token
        - name: REPO_FULL_NAME
          value: SREYardship/PlatformUp2Date
        - name: GITEA_HOST_URL
          value: git.sreyardship.com
        - name: SHA
          value: $(params.sha)
        - name: DESCRIPTION
          value: "Build has started"
        - name: STATE
          value: $(params.pipelineStatus)
        - name: TARGET_URL
          value: https://dashboard.ci.sreyardship.com/#/namespaces/platformup2date/pipelineruns

