apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: pr-build-test
spec:
  params:
    - name: url
      description: "Repository URL to clone from."
      type: string
    - name: revision
      description: "Revision to checkout. (branch, tag, sha, ref, etc...)"
      type: string
      default: ""
    - name: sha
      description: "sha being worked on"
      type: string
      default: ""
    - name: branch_name
      description: "Sanitized branch name used as prerelease label"
      type: string
  workspaces:
    - name: source
    - name: ssh-directory
  tasks:
    - name: set-pending-status
      taskRef:
        resolver: cluster
        params:
          - name: name
            value: gitea-set-status
          - name: namespace
            value: tekton-pipelines
      params:
        - name: GITEA_TOKEN_SECRET_NAME
          value: git-ci-status-token
        - name: REPO_FULL_NAME
          value: SREYardship/PlatformUp2Date
        - name: GITEA_HOST_URL
          value: git.sreyardship.com
        - name: SHA
          value: $(params.sha)
        - name: DESCRIPTION
          value: "PR pipeline has started"
        - name: STATE
          value: pending
        - name: CONTEXT
          value: ci/pr-build-test
        - name: TARGET_URL
          value: https://dashboard.ci.sreyardship.com/#/namespaces/platformup2date/pipelineruns

    - name: git-clone
      taskRef:
        resolver: cluster
        params:
          - name: name
            value: git-clone
          - name: namespace
            value: tekton-pipelines
      params:
        - name: url
          value: "$(params.url)"
        - name: revision
          value: "$(params.revision)"
      workspaces:
        - name: output
          workspace: source
        - name: ssh-directory
          workspace: ssh-directory

    - name: build-backend-jar
      runAfter:
        - git-clone
      taskRef:
        resolver: cluster
        params:
          - name: name
            value: nix-devshell-run
          - name: namespace
            value: tekton-pipelines
      params:
        - name: script
          value: backend/ci/bin/build.sh
      workspaces:
        - name: source
          workspace: source

    - name: build-backend-native
      runAfter:
        - git-clone
      taskRef:
        resolver: cluster
        params:
          - name: name
            value: nix-devshell-run
          - name: namespace
            value: tekton-pipelines
      params:
        - name: script
          value: backend/ci/bin/build-native.sh
      workspaces:
        - name: source
          workspace: source

    - name: unit-test
      runAfter:
        - build-backend-jar
      taskRef:
        resolver: cluster
        params:
          - name: name
            value: nix-devshell-run
          - name: namespace
            value: tekton-pipelines
      params:
        - name: script
          value: backend/ci/bin/unit-test.sh backend/build/classes
      workspaces:
        - name: source
          workspace: source

    - name: build-and-publish-container
      runAfter:
        - build-backend-native
      taskRef:
        resolver: cluster
        params:
          - name: name
            value: container-build-push
          - name: namespace
            value: tekton-pipelines
      params:
        - name: dockerfile
          value: backend/src/main/docker/Dockerfile.native-ci
        - name: context
          value: backend
        - name: image-name
          value: platformup2date/backend
        - name: tag
          value: $(params.branch_name)
        - name: env-secret
          value: registry-env
      workspaces:
        - name: source
          workspace: source

  finally:
    - name: pipeline-state
      displayName: "Pipeline Final State"
      taskRef:
        resolver: cluster
        params:
          - name: name
            value: gitea-set-status
          - name: namespace
            value: tekton-pipelines
      params:
        - name: GITEA_TOKEN_SECRET_NAME
          value: git-ci-status-token
        - name: REPO_FULL_NAME
          value: SREYardship/PlatformUp2Date
        - name: GITEA_HOST_URL
          value: git.sreyardship.com
        - name: SHA
          value: $(params.sha)
        - name: DESCRIPTION
          value: "PR pipeline has finished"
        - name: STATE
          value: "$(tasks.status)"
        - name: CONTEXT
          value: ci/pr-build-test
        - name: TARGET_URL
          value: https://dashboard.ci.sreyardship.com/#/namespaces/platformup2date/pipelineruns
