version: '3.8'

services:
  frontend:
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile.dev
    environment:
      - REACT_APP_BASE_URL=http://localhost:8080
    ports:
      - '3000:3000'
    depends_on:
      - backend
  backend:
    container_name: backend
    build:
      context: backend/server
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - '8080:8080'
