apiVersion: tekton.dev/v1 # or tekton.dev/v1beta1
kind: Task
metadata:
  name: list-files
spec:
  workspaces:
  - name: source
    description: where the sourcecode is
  steps:
  - name: list-files
    image: ubuntu
    securityContext:
      runAsNonRoot: true
      runAsUser: 65532
    script: |
      ls -R "$(workspaces.source.path)"
