---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-ci-status-token
  namespace: platformup2date
spec:
  encryptedData:
    token: AgAVVf6nEogxmQoIycNWbfIfgy8ZW4OdXqRrMBqTqaEsqi3ws+XOe0tod7udarcMDXAq03Yo+lTP4vQbl5NWoQvBMjoSLNPcuVbjW25RKJ9UT/kAYS5hO6Os/9csu4E+r3TKZ7IUW6L9AvB7RWM2CZpaeDkptqDAmimQtppApP37v9Y6LWoVgZkJ3+yPm4d+GZ3gqJs1E4LzKhobAEfmk/rA4uNOqV5jQp72Dg1szlqBVFJJ+fIWZlfyPsrhc94iUQfhJJAmgMyPeZAFp642uy8AtRBj4oyZrw1cZq1qDvMuM9QXCzdCXBdOex3go22l3UbPTciWkrbBaEUFk5I23Z4yY0zf0PZXPIB5OzbaayvbMbheyXEoTgcADHYYILMfzSptLvpXHmh7VlqMRA05C74eEgcpugL50+JBi+XLJxu8JqcYMuPaieD5tUbpJUDjCsHVfj0FNgI7qEvFfVNlStLdagYn9eiozkO7Uq+N7ZzD32sL1mOZVpWXHwlOnuFCsTt4qf0kdrz2RsB1aYl+Bhl41YOnq2J/cqMjZPOnJmpl6EVXhh76mP62lj9YRC4VBESl9KZxF8VnXVg3O+fhJupt8apMLVqSC1GuaA8y636a/Rzg+jYcMt1lz9ugR70u9krBZRddsyZ08jlksvRf1XZOPsUYhFy/krku5YSVlILtShfVA1vv79WcQPcea3kt1AFjr+yWfqn636+v4MJ+qWJ4EN5n/oa9jAodhcScHKlYDw4rUVSLbcdG
  template:
    metadata:
      creationTimestamp: null
      name: git-ci-status-token
      namespace: platformup2date
