apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: registry-env
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-backend
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: registry-env
  refreshInterval: 1h
  data:
    - secretKey: REGISTRY_USER
      remoteRef:
        key: ci/registry
        property: username
    - secretKey: REGISTRY_PASSWORD
      remoteRef:
        key: ci/registry
        property: password
