apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: platformup2date-listener-interceptor
  labels:
    istio.io/ingress-use-waypoint: "true"
spec:
  serviceAccountName: tekton-triggers-gitea-platformup2date
  triggers:
  - name: gitea-listener
      #    interceptors:
      #    - cel:
      #        filter: "body.ref == 'refs/heads/main'"
    bindings:
    - ref: clone-test-binding
    template:
      ref: clone-test
---
