apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: platformup2date
spec:
  params:
  - name: ref
    description: The Git commit revision
  - name: sha
    description: The Git commit sha
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: clone-test-
    spec:
      pipelineRef:
        name: build-test
      podTemplate:
        securityContext:
          fsGroup: 65532
      params:
      - name: url
        value: git@git.sreyardship.com:SREYardship/PlatformUp2Date.git
      - name: revision
        value: $(tt.params.ref)
      - name: sha
        value: $(tt.params.sha)
      workspaces:
        - name: ssh-directory
          secret:
            secretName: git-creds
        - name: source
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteMany
              storageClassName: ceph-filesystem
              resources:
                requests:
                  storage: 2Gi
---

apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: platformup2date-binding
  namespace: tekton-pipelines
spec:
  params:
  - name: ref
    value: $(body.ref)
  - name: sha
    value: $(body.head_commit.id)

---
